In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('intrusion_data_combined.csv')
data

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,icmp,20,2,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,45,2,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,icmp,50,4,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,dos
3,0,icmp,25,2,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,icmp,25,2,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135968,0,icmp,25,2,315,2537,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
135969,0,icmp,25,2,238,6882,0,0,0,0,...,253,1.00,0.00,0.14,0.05,0.00,0.00,0.00,0.00,normal
135970,0,udp,50,2,54,55,0,0,0,0,...,254,1.00,0.01,0.81,0.00,0.00,0.00,0.00,0.00,normal
135971,0,icmp,25,2,228,5210,0,0,0,0,...,255,1.00,0.00,0.01,0.04,0.00,0.00,0.00,0.00,normal
135972,282,icmp,20,2,160,597,0,0,0,2,...,14,0.05,0.84,0.00,0.00,0.00,0.00,0.82,0.00,r2l

In [3]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,icmp,20,2,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,45,2,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,icmp,50,4,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,dos
3,0,icmp,25,2,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,icmp,25,2,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [4]:
data.shape

(135973, 42)

In [5]:
data.isnull().values.any()

False

In [6]:
data.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
label                          0
dtype: int64

In [7]:
X = data[['duration','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins']]
Y = data['label']

In [8]:
X.shape
Y.shape

(135973,)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [10]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(108778, 10)
(27195, 10)
(108778,)
(27195,)

In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(x_train)
# X_test_scaled = scaler.transform(x_test)

numeric_features = X.select_dtypes(include=["int64", "float64"]).columns
categorical_features = X.select_dtypes(include=["object"]).columns

numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder())
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Step 5: Apply PCA for feature reduction
pca = PCA(n_components=10)  # Adjust the number of components based on your dataset

# Step 6: Create and train the classifier (Random Forest)
classifier = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('pca', pca),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42))
])

In [12]:
classifier.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  Index(['duration', 'service', 'flag', 'src_bytes', 'dst_bytes', 'land',
       'wrong_fragment', 'urgent', 'hot', 'num_failed_logins'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder())]),
                                                  Index([], dtype='object'))])),
                ('pca', PCA(n_components=10)),
                ('classifier', RandomForestClassifier(random_state=42))])

In [13]:
y_pred = classifier.predict(x_test)

In [14]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [15]:
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(report)

Accuracy: 0.9730465159036588
Confusion Matrix:
[[ 9756    78    11     0     0]
 [   74 14221    42    12     8]
 [  421    16  2114     2     0]
 [    0    46     1   365     1]
 [    0     9    11     1     6]]
Classification Report:
              precision    recall  f1-score   support

         dos       0.95      0.99      0.97      9845
      normal       0.99      0.99      0.99     14357
       probe       0.97      0.83      0.89      2553
         r2l       0.96      0.88      0.92       413
         u2r       0.40      0.22      0.29        27

    accuracy                           0.97     27195
   macro avg       0.85      0.78      0.81     27195
weighted avg       0.97      0.97      0.97     27195

In [16]:
# Assuming 'new_data' is a list of 10 values for the features you want to predict
new_data = [0,20,2,334,0,0,0,0,0,0]

# Create a new dataframe for the new data
new_data_df = pd.DataFrame([new_data], columns=['duration', 'service', 'flag', 'src_bytes', 'dst_bytes',
                                                   'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins'])

    # Use the trained classifier to make predictions on the new data
    y_pred_new_data = classifier.predict(new_data_df)

    # Check if the predicted label is normal (0) or malware (1)
    if y_pred_new_data[0] == "normal":
        print("The data is predicted as normal.")
    elif y_pred_new_data[0] =="dos":
        print("The data is predicted as dos.")
    elif y_pred_new_data[0]=="probe":
        print("The data is predicted as probe.")
    elif y_pred_new_data[0]=="r2l":
        print("The data is predicted as r2l.")

The data is predicted as r2l.

In [17]:
import pickle
# Specify the file path where you want to save the pickle file
file_path = 'classifier.pkl'

# Open the file in binary write mode
with open(file_path, 'wb') as file:
  
    pickle.dump(classifier, file)